variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dsonar.coverage.jacoco.xmlReportPaths=report1.xml,report2.xml"
  MAVEN_SKIP_TEST: "-s settings.xml -Dmaven.test.skip=true"

# Maven avec JDK 20
image: maven:3-eclipse-temurin-20
services:
  - name: vincensini/zoomysql
    alias: mysql

cache:
  paths:
    - .m2/repository

stages:
  - build
  - bdd
  - test
  - quality
  - deployment

build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS clean'
    - 'mvn $MAVEN_CLI_OPTS compile'

bdd:
  stage: bdd
  image: vincensini/zoomysql:latest
  script:
    - 'echo base chargée'

testing:
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS test'

quality:
  stage: quality
  script:
    - 'mvn $MAVEN_CLI_OPTS jacoco:report'
    - 'mvn $MAVEN_CLI_OPTS verify'
    - 'mvn $MAVEN_CLI_OPTS sonar:sonar'

  allow_failure: false

deployment:
  stage: deployment
  script:
    - 'mvn package $MAVEN_SKIP_TEST'
    - 'mvn clean deploy $MAVEN_SKIP_TEST'


